DELETE http://localhost:8081/produto/deletar
Content-Type: application/json

{
  "id": 1,
  "codigoProduto": 1,
  "nome": "GTA V",
  "descricao": "Um jogo de mundo aberto que te possibilita explorar aleatoriamente ou fazer o modo história se desejar.",
  "preco": 99.99,
  "qtdEstoque": 5
}