POST http://localhost:8081/colaborador/salvar
Content-Type: application/json

{
  "nome": "Murilo Santos",
  "senha":"31972c92a892d3073c2232867ad961fde1915c639577efcb4413ea251214a713",
  "email": "murilos@gmail.com"

}